<!-- scripts and css files for editor starts here -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/js/froala_editor.min.js" integrity="sha512-S8KBWiPEJnWrSuxolmWWNhRVX1juJA7T8TrGMKO5Pz44jjtubdS13M6jtTSYZFeoc0y2kImYEV+ofCl3G09fWw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/js/froala_editor.pkgd.min.js" integrity="sha512-z5HDE+iOljozuFUMByK6Y/qE9xv9M/c6QpwxPh60slE2LOP9Oz13Z1LueYX5E3K4u9NmFp6b1rGW8wVxSVnDpA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/js/plugins/file.min.js" integrity="sha512-+WDF7X7JkHFUlp9hp1awm+Dfzm+PHRWS4ax8uazxg5tckboTfkXUtHf5ZmbM4h9+kxqKJJYDfb3ixrf1Pk2yKw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/js/plugins/files_manager.min.js" integrity="sha512-xnN9Zt3Sx+O6yzp7jQDIDc2hl+m9e0dHQ/8oTWWtTFlIYR/gH2WKH6zDKf2MZCkapUuzlk+uiz0kAjvxBCLjIw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/js/plugins/draggable.min.js" integrity="sha512-LDNOQXGz3TL7X3yzSbCki5Hg8Bq5lZnTUvKn8daLrPKEEvjKzR9sxiUP5e56/O5TbbW6zWdUEPa2s+Mzc5qhdQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/js/plugins/image.min.js" integrity="sha512-1WwO3DuvTXPKD1EQD09eRkfgI6zb38b4q/0o40osz2bIBjO2mf5OIIT5VJFTb4lWyUFLH3hfoIhNLwdSviL4gQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/js/plugins/image_manager.min.js" integrity="sha512-l6Oymb1IzEN7hg+iMgW2BEGZMlUrOmyg6ZlyoT9jTDyJLnA1nRKvaHhi9+Ncr1mVGldRGmlvdZ1zRo8/W155Ng==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/css/plugins/draggable.min.css" integrity="sha512-PICvIi5GpUi2WRcv+5ykfjpq/S1JccEgRDjh/5sg4JJTBUeWfVrxuwNoCckoWAzkjMQ3CW/fnaYNR4BuGRgzOQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/css/plugins/file.min.css" integrity="sha512-7Bo5Iz89vp0aiL3nHz4WfHQ/IAYkjBIP1DvirXvuG9sq4sO2nUaPcriv593FNJPmOLwda63+yrNYU2FUO6nwuw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/css/plugins/files_manager.min.css" integrity="sha512-xnywLaZKPodB3u9AzCBv91gkQ2/IpT/1TkB9zmcSX3JlWcUXSzweZlIu6Nn/aOi1y2dU2uaZGt3GBxtpIzzYoQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/css/plugins/image.min.css" integrity="sha512-iNX5fYNycmE+dA2Pzd+WxeIshkibDu1JCBymiZZow7pH62PZ5xSyzFVIziNwvG/loOTBsskjTO2dHAp0PKLI3w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/css/plugins/image_manager.min.css" integrity="sha512-NEnSnHrRoJxXfJVeWRB8clnFl/cbIRPUJi/JyG5dQe19xPzTJviokBgs1h83+JXhwC1Uk7Y097pp3f8qn+FOJw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/css/froala_style.min.css" integrity="sha512-w2/YRA6wzSsxxe1M+0TFinZuael6eQr8A3yXbBP6tKM+a0DbChos40lDJiB+jMgxJUK29rSn8ouh9I6RaGRXew==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/4.0.14/css/froala_editor.min.css" integrity="sha512-X5etY6JrAxOdXx/oyB9sqZ4IYEx8539ccjcxxOn0NtMZ7Tgl8WzMOjDe5Hw0//gEsiZpt7tQFfAawQA4cId0rw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<!-- scripts and css files for editor ends here -->